#!/bin/bash
set -e

SCRIPT=$(readlink -f $0)
SCRIPT_ROOT_PATH=$(dirname $SCRIPT)

function make_link {
    echo "$2 -> $1"
    ln -f -s $1 $2
}

make_link $SCRIPT_ROOT_PATH/profile ~/.profile
make_link $SCRIPT_ROOT_PATH/zshrc ~/.zshrc
make_link $SCRIPT_ROOT_PATH/tmux.conf ~/.tmux.conf
make_link $SCRIPT_ROOT_PATH/gitconfig ~/.gitconfig
make_link $SCRIPT_ROOT_PATH/selected_editor ~/.selected_editor
make_link $SCRIPT_ROOT_PATH/hgrc ~/.hgrc
make_link $SCRIPT_ROOT_PATH/init.gradle ~/.gradle/init.gradle

make_link $SCRIPT_ROOT_PATH/Xresources ~/.Xresources
xrdb -merge ~/.Xresources

touch ~/.zshrc_private
chmod u=rw,g=,o= ~/.zshrc_private

make_link ~/cfg/emacs ~/emacs
make_link ~/cfg/emacs/init.el ~/.emacs
