# -*- mode: shell-script; -*-

export ZSH=/home/user/.oh-my-zsh

ZSH_THEME="robbyrussell"

HIST_STAMPS="dd.mm.yyyy"

export WORKON_HOME="$HOME/.virtualenvs"

ZSH_CUSTOM=$HOME/.zsh-custom
plugins=(
    git svn hg
    tmux
    extract
    cp
    docker
    go
    lein
    nvm npm node
    python pip fabric virtualenvwrapper
    debian systemd
    gradle
)

source $ZSH/oh-my-zsh.sh
source $ZSH_CUSTOM/kubectl
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

setopt nosharehistory
unsetopt auto_cd

export LANG="en_US.UTF-8"
export LC_PAPER="ru_RU.UTF-8"
export LC_MEASUREMENT="ru_RU.UTF-8"
export LC_TIME="ru_RU.UTF-8"
export LC_ALL="en_US.UTF-8"

alias free='free --human --lohi'
alias df='df --human-readable'
alias ll='ls -lav --classify --human-readable --group-directories-first'
alias sreload='source ~/.zshrc'

alias em="$EDITOR"
alias vem="$VISUAL"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

function add_to_path {
    PATH="$1:$PATH"
}

if [ -f ~/.zshrc_private ]; then
  . ~/.zshrc_private
fi

typeset -U path cdpath fpath manpath
add_to_path "$HOME/bin"
add_to_path "$HOME/.local/bin"
add_to_path "$UBUNTU_CFG_ROOT/bin"
add_to_path "$HOME/local/bin"
add_to_path "$HOME/.cask/bin"
add_to_path "$GROOVY_HOME/bin"
add_to_path "$HOME/.cabal/bin"
add_to_path "$HOME/.evm/bin"


PATH="$HOME/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="$HOME/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="$HOME/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"$HOME/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=$HOME/perl5"; export PERL_MM_OPT;

export GODEV_HOME="$HOME/godev"
export GOPATH="$GODEV_HOME"
mkdir -p $GODEV_HOME
add_to_path "$GODEV_HOME/bin"
add_to_path "/usr/lib/go/bin/"
