#!/bin/bash
# -*- mode: shell-script; -*-

wget -nv -O- https://download.calibre-ebook.com/linux-installer.py | \
    python -c "import sys; main=lambda x,y:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main('~/calibre-bin', True)"
