#!/bin/bash
# -*- mode: shell-script; -*-

go get -u github.com/nsf/gocode
go get -u github.com/rogpeppe/godef
go get -u github.com/jstemmer/gotags
go get -u github.com/kisielk/errcheck
go get -u golang.org/x/tools/cmd/guru
go get -u github.com/golang/lint/golint
go get -u golang.org/x/tools/cmd/gorename
go get -u golang.org/x/tools/cmd/goimports
go get -u github.com/dghubble/sling
go get -u github.com/stretchr/testify
go get -u golang.org/x/tools/cmd/cover
go get -u github.com/mattn/goveralls
go get -u github.com/golang/lint/golint
go get -u github.com/GeertJohan/fgt
go get -u github.com/stretchr/gorc
sudo -E go get -u golang.org/x/tools/cmd/godoc
