#!/bin/bash
# -*- mode: shell-script; -*-

function install {
    sudo apt-get install -y $@
}

sudo apt-get update
install curl
install wget
install ncurses-dev
install exuberant-ctags
 
echo "install GNU global..."
pushd ~/src/
wget http://tamacom.com/global/global-6.5.1.tar.gz
tar zxvf global-6.5.1.tar.gz
cd global-6.5.1
./configure --prefix=$HOME/local --with-exuberant-ctags=/usr/bin/ctags
make && make install
popd

echo "install pygments..."
sudo pip install pygments==1.6
 
echo "$0 done."
