#!/bin/bash
# -*- mode: shell-script; -*-

curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
chmod +x kubectl
sudo mv ./kubectl /usr/local/bin/kubectl

kubectl completion zsh > $HOME/.zsh-custom/kubectl
