#!/bin/bash
# -*- mode: shell-script; -*-

function install {
    sudo apt-get install -y $@
}

function remove {
    sudo apt-get purge $@
}

install aptitude
install tmux xclip
install emacs emacs-goodies-el silversearcher-ag
install krusader
install tilda
install cmake
install htop
install thunderbird
install network-manager-openconnect
install virtualbox
install git git-flow
install subversion
install meld
install filezilla
install dconf-cli dconf-editor
install wmctrl
install sshpass
install unetbootin
install ubuntu-restricted-extras
install sox

install python-pip
install python-dev

remove unity-scope-video-remote
remove unity-scope-musicstores

gsettings set org.gnome.desktop.interface enable-animations false
gsettings set org.gnome.shell.extensions.dash-to-dock animate-show-apps false
