#!/bin/bash
# -*- mode: shell-script; -*-

function install {
    sudo apt-get install -y $@
}

function remove {
    sudo apt-get purge $@
}

install tmux xclip
install emacs emacs-goodies-el silversearcher-ag
install krusader konsole
install tilda
install liferea
install cmake
install htop
install thunderbird
install firefox
install network-manager-openconnect
install workrave
install virtualbox
install git subversion meld
install filezilla
install dconf-cli
install wmctrl
install sshpass
install unetbootin

install wireshark
sudo dpkg-reconfigure wireshark-common
sudo usermod -a -G wireshark $USER

install python-pip
sudo pip install thefuck --upgrade

remove unity-scope-video-remote unity-scope-musicstores
