#!/bin/bash
# -*- mode: shell-script; -*-
set -x

sudo apt install -y zsh curl

ZSH_CUSTOM=~/.zsh
mkdir -p ${ZSH_CUSTOM}

if [ ! -f "${ZSH_CUSTOM}/antigen.zsh" ]; then
    curl -L git.io/antigen > "${ZSH_CUSTOM}/antigen.zsh"
fi

kubectl completion zsh > ${ZSH_CUSTOM}/kubectl
