#!/bin/bash
# -*- mode: shell-script; -*-
set -x
sudo apt install -y zsh zsh-syntax-highlighting curl
mkdir -p ~/.zsh-custom

if [ ! -d "$HOME/.oh-my-zsh" ]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

kubectl completion zsh > $HOME/.zsh-custom/kubectl
